app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;
use App\Event;

Route::group(['middleware' => ['web']], function () {
	Route::auth();
	Route::get('/registration/{user}/{confirmation_code}', 'Auth\RegisterController@activate')
			 ->name('registration.activate');

	Route::group(['prefix' => 'social'], function(){
		Route::get('facebook', 'SocialAuthController@facebook');
		Route::get('facebook/callback', 'SocialAuthController@facebookCallback');
		Route::get('google', 'SocialAuthController@google');
		Route::get('google/callback', 'SocialAuthController@googleCallback');
	});


	// Route for purchase ticket form submission
	Route::post('events/{event}/tickets', 'OrderController@postPurchaseTicket')
	->name('events.tickets');
	Route::get('order/prepare', 'OrderController@getPrepareOrder')
	->name('orders.prepare');
	Route::post('orders/{order}', 'OrderController@form_submit')
	->name('orders.form_submit');
	Route::get('orders/{order}', 'OrderController@show')
	->name('orders.show');
    Route::post('orders/{order}/pay', 'OrderController@postInitPayment')
        ->name('orders.payment');
    Route::get('orders/{order}/resurrect', 'OrderController@resurrectOrder')
        ->name('orders.resurrect');
	Route::post('payment/{order}/failed', 'OrderController@postFailedTransaction')
	->name('orders.failed_transaction');
	Route::post('payment/{order}/success', 'OrderController@postSuccessfulTransaction')
	->name('orders.successful_transaction');

	Route::get('events/{event}/guests', 'EventController@guestList')->name('events.guests');
	Route::get('events/{event}/export_codes', 'EventController@exportCodes')->name('events.export_codes');
	Route::get('events/{event}/export_csv', 'EventController@exportCsv')->name('events.export_csv');
	Route::get('search', 'EventController@search')->name('search');

	Route::resource('organizers', 'OrganizerController');

	Route::get('events/saved', 'EventController@savedEvents')->name('events.saved');
	Route::get('events/{event}/bookmark', 'EventController@bookmark')->name('events.bookmark');
	Route::resource('events', 'EventController');
	Route::resource('passes', 'PassController',
	['only' => ['index', 'show']]);

	Route::get('/', 'HomeController@getIndex')->name('home');
	Route::get('/browse', 'HomeController@getBrowse')->name('browse');

	Route::get('/terms-of-service', function(){
		return view('pages.tos');
	})->name('tos');

	Route::get('/about-us', function(){
		return view('pages.about');
	})->name('about');

	Route::get('/privacy-policy', function(){
		return view('pages.pp');
	})->name('pp');

	Route::get('/my_profile', 'ProfileController@edit')->name('profiles.self.edit');
	Route::get('/profiles/{user}/edit', 'ProfileController@edit')->name('profiles.edit');
	Route::post('/profiles/{user}/edit', 'ProfileController@update')->name('profiles.update');
});

Route::group([
		'middleware' => ['auth:api', 'api'],
		'prefix' => 'api',
		'as' => 'api::',
	], function () {

		Route::get('events/{event}/bookmark', 'Api\EventController@bookmark')->name('events.bookmark');
		Route::post('events/{event}/scan', 'Api\EventController@scan')->name('events.scan');
		Route::resource('events', 'Api\EventController',
			['except' => ['create', 'edit']]);
		Route::resource('passes', 'Api\PassController',
			['only' => ['index', 'show']]);

		Route::post('orders', 'Api\OrderController@placeOrder');
		Route::post('order/pay/{order}', 'Api\OrderController@postConfirmBkashPayment');

		Route::get('userinfo', 'Api\BasicController@userinfo');
});



Route::post('oauth/provider/{provider}', 'SocialAuthController@authorizeProviderToken')
	->middleware('api');

Route::post('api/users', 'Auth\RegisterController@apiCreate')->middleware(['api', 'auth:api']);

app/Organizer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organizer extends Model
{
    use Metabble;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'about'];

    /**
     * Get the owner of the event
     */
    public function owner()
    {
    	return $this->belongsTo('App\User', 'owner_id');
    }

    /**
     * Get events owned by the organizer
     */
    public function events()
    {
        return $this->hasMany('App\Event', 'organizer_id');
    }
}

app/Http/Controllers/OrganizerController.php
<?php

namespace App\Http\Controllers;

use App\Organizer;
use App\Meta;
use Auth;
use Input;
use Session;

use Illuminate\Http\Request;

use App\Http\Requests;

class OrganizerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.organizers.index', [
            'organizers' => Auth::user()->organizers()->paginate(20)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Organizer::class);

        return view('dashboard.organizers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Requests\StoreOrganizer  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StoreOrganizer $request)
    {
        $this->authorize('create', Organizer::class);
        $organizer = Organizer::create(Input::all());

        $organizer->owner_id = Auth::id();

        foreach(Input::get('meta') as $key => $value){
            if(trim($value) == '') continue;
            $organizer->meta()->save(new Meta(['key' => $key, 'value' => $value]));
        }
        $organizer->save();

        Session::flash('message', 'Organizer created!');
        return Redirect(route('organizers.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $organizer = Organizer::find($id);

        return view('dashboard.organizers.show', [
            'organizer' => $organizer,
            'events' => $organizer->events()->where([
                ['privacy', 'public'],
                ['live', 1]
            ])->paginate(12)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $organizer = Organizer::find($id);
        $this->authorize('update', $organizer);

        return view('dashboard.organizers.edit')->with('organizer', $organizer);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Requests\StoreOrganizer  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\StoreOrganizer $request, $id)
    {
        $organizer = Organizer::find($id);
        $this->authorize('update', $organizer);
        $organizer->name = Input::get('name');
        $organizer->about = Input::get('about');

        foreach(Input::get('meta') as $key => $value){
            $organizer->update_meta($key, $value);
        }
        $organizer->save();

        Session::flash('message', 'Update saved!');
        return Redirect(route('organizers.edit', $id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $organizer = Organizer::find($id);
        $this->authorize('delete', $organizer);
        Meta::where('entity_type', 'App\Organizer')
            ->where('entity_id', $id)
            ->delete();

        $organizer->delete();

        Session::flash('message', 'Organizer Deleted!');
        return Redirect(route('organizers.index'));
    }
}

resources/views/dashboard/organizers/snippets/no-organizers.blade.php
<section class="container section-gap">
    <div class="row">
        <div class="col-sm-offset-3 col-sm-6">
            <div class="no-organizer-text alert alert-warning">Currently you have <span>no organizer </span>.<br>Please create it by clicking <br><span>CREATE NEW</span> <br>button if you want to.</div>
        </div>
    </div>
</section>

resources/views/dashboard/organizers/snippets/org-general-info.blade.php
    <!-- General Information about Organizer -->
    <div class="row">
        <div class="col-md-4">

            <!-- Heading -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="organizer-info-heading">
                        General Information
                    </div>
                </div>
            </div>

            <!-- Name -->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="name">Organizer Name</label>
                    <input type="text" class="form-control" name="name" id="name" value="{{isset($organizer)? $organizer->name : ''}}">
                </div>
            </div>
            <!-- End -->

            <!-- About -->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="about">About Organizer</label>
                    <textarea rows="6" type="text" class="form-control" name="about" id="about">{{isset($organizer)? $organizer->about : ''}}</textarea>
                </div>
            </div>
            <!-- End-->
        </div>

        <!-- Social link -->
        <div class="col-sm-6 col-md-4" >

            <!--Heading -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="organizer-info-heading-small">
                        Social Network links
                    </div>
                </div>
            </div>
            <!-- End -->

            <!-- Website Link -->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="website">Website</label>
                    <input type="text" class="form-control" name="meta[website]" id="website" value="{{isset($organizer)? $organizer->meta('website') : ''}}">
                </div>
            </div>
            <!-- End -->

            <!-- Facebook Link -->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="facebook">Facebook</label>
                    <input type="text" class="form-control" name="meta[social_facebook]" id="facebook" value="{{isset($organizer)? $organizer->meta('social_facebook') : ''}}">
                </div>
            </div>
            <!-- End -->

            <!-- Twitter -->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="twitter">Twitter</label>
                    <input type="text" class="form-control" name="meta[social_twitter]" id="twitter" value="{{isset($organizer)? $organizer->meta('social_twitter') : ''}}">
                </div>
            </div>
            <!-- End -->
        </div>

        <!-- Other Settings -->
        <div class="col-sm-6 col-md-4">

            <!-- Colors -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="organizer-info-heading-small">
                        Contact Info
                    </div>
                </div>
            </div>

            <!-- Contact No Home-->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="text">Home</label>
                    <input placeholder="format:+880-1XXX-XXX-XXX" type="text" class="form-control" name="meta[contact_home]" id="contact_home" value="{{isset($organizer)? $organizer->meta('contact_home') : ''}}">
                </div>
            </div>
            <!-- End -->

            <!-- Contact No -->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="text">Work</label>
                    <input placeholder="format:+880-1XXX-XXX-XXX" type="text" class="form-control" name="meta[contact_work]" id="contact_work" value="{{isset($organizer)? $organizer->meta('contact_work') : ''}}">
                </div>
            </div>
            <!-- End -->

            <!-- Email Address -->
            <div class="row field-hint">
                <div class="col-sm-12">
                    <label for="background">Email Address</label>
                    <input type="text" class="form-control" name="meta[email_address]" id="email_address" value="{{isset($organizer)? $organizer->meta('email_address') : ''}}">
                </div>
            </div>
            <!-- End -->

        </div>
    </div>

resources/views/dashboard/organizers/snippets/organizer.blade.php
<tr id="organizer-{{$organizer->id}}">
        <td class="organizer-name-list col-xs-10">
            <a href="{{route('organizers.show', $organizer->id)}}">
                {{$organizer->name}}
            </a>
        </td>
        <td class="organizer-edit col-xs-1">
            <a role="button" href="{{route('organizers.edit', $organizer->id)}}">
                <i class="fa fa-pencil"></i>
            </a>
        </td>
        @can('delete', $organizer)
        <td class="organizer-delete col-xs-1">
            <form  action="{{route('organizers.destroy', $organizer->id)}}" method="post">
                <button type="submit">
                    <i class="fa fa-trash-o"></i>
                </button>
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
            </form>
        </td>
        @endcan
    </tr>