app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;
use App\Event;

Route::group(['middleware' => ['web']], function () {
	Route::auth();
	Route::get('/registration/{user}/{confirmation_code}', 'Auth\RegisterController@activate')
			 ->name('registration.activate');

	Route::group(['prefix' => 'social'], function(){
		Route::get('facebook', 'SocialAuthController@facebook');
		Route::get('facebook/callback', 'SocialAuthController@facebookCallback');
		Route::get('google', 'SocialAuthController@google');
		Route::get('google/callback', 'SocialAuthController@googleCallback');
	});


	// Route for purchase ticket form submission
	Route::post('events/{event}/tickets', 'OrderController@postPurchaseTicket')
	->name('events.tickets');
	Route::get('order/prepare', 'OrderController@getPrepareOrder')
	->name('orders.prepare');
	Route::post('orders/{order}', 'OrderController@form_submit')
	->name('orders.form_submit');
	Route::get('orders/{order}', 'OrderController@show')
	->name('orders.show');
    Route::post('orders/{order}/pay', 'OrderController@postInitPayment')
        ->name('orders.payment');
    Route::get('orders/{order}/resurrect', 'OrderController@resurrectOrder')
        ->name('orders.resurrect');
	Route::post('payment/{order}/failed', 'OrderController@postFailedTransaction')
	->name('orders.failed_transaction');
	Route::post('payment/{order}/success', 'OrderController@postSuccessfulTransaction')
	->name('orders.successful_transaction');

	Route::get('events/{event}/guests', 'EventController@guestList')->name('events.guests');
	Route::get('events/{event}/export_codes', 'EventController@exportCodes')->name('events.export_codes');
	Route::get('events/{event}/export_csv', 'EventController@exportCsv')->name('events.export_csv');
	Route::get('search', 'EventController@search')->name('search');

	Route::resource('organizers', 'OrganizerController');

	Route::get('events/saved', 'EventController@savedEvents')->name('events.saved');
	Route::get('events/{event}/bookmark', 'EventController@bookmark')->name('events.bookmark');
	Route::resource('events', 'EventController');
	Route::resource('passes', 'PassController',
	['only' => ['index', 'show']]);

	Route::get('/', 'HomeController@getIndex')->name('home');
	Route::get('/browse', 'HomeController@getBrowse')->name('browse');

	Route::get('/terms-of-service', function(){
		return view('pages.tos');
	})->name('tos');

	Route::get('/about-us', function(){
		return view('pages.about');
	})->name('about');

	Route::get('/privacy-policy', function(){
		return view('pages.pp');
	})->name('pp');

	Route::get('/my_profile', 'ProfileController@edit')->name('profiles.self.edit');
	Route::get('/profiles/{user}/edit', 'ProfileController@edit')->name('profiles.edit');
	Route::post('/profiles/{user}/edit', 'ProfileController@update')->name('profiles.update');
});

Route::group([
		'middleware' => ['auth:api', 'api'],
		'prefix' => 'api',
		'as' => 'api::',
	], function () {

		Route::get('events/{event}/bookmark', 'Api\EventController@bookmark')->name('events.bookmark');
		Route::post('events/{event}/scan', 'Api\EventController@scan')->name('events.scan');
		Route::resource('events', 'Api\EventController',
			['except' => ['create', 'edit']]);
		Route::resource('passes', 'Api\PassController',
			['only' => ['index', 'show']]);

		Route::post('orders', 'Api\OrderController@placeOrder');
		Route::post('order/pay/{order}', 'Api\OrderController@postConfirmBkashPayment');

		Route::get('userinfo', 'Api\BasicController@userinfo');
});



Route::post('oauth/provider/{provider}', 'SocialAuthController@authorizeProviderToken')
	->middleware('api');

Route::post('api/users', 'Auth\RegisterController@apiCreate')->middleware(['api', 'auth:api']);

app/Http/Controllers/Api/EventController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;

use Hshn\Base64EncodedFile\HttpFoundation\File\Base64EncodedFile;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Event;
use App\Ticket;
use App\Pass;
use App\Organizer;
use App\ScanLog;
use Auth;
use Input;
use Session;
use \DateTime;
use MediaUploader;
use Validator;
use Response;

class EventController extends Controller
{

    /**
     * Validator for event requests.
     */
    public function validator($request){
        $messages = [
            'title.required' => 'You must specify an event title.',
            'title.min:5' => 'Event title must be at least 5 characters long.',
            'tickets.required' => 'You must set at least one ticket type.',
            'tickets.*.name.required_unless' => 'Ticket name is a required field.',
            'tickets.*.price.required_unless' => 'Ticket price is a required field.',
            'tickets.*.price.numeric' => 'Invalid ticket price given.',
            'tickets.*.quantity.required_unless' => 'Ticket quantity is a required field.',
            'tickets.*.quantity.integer' => 'Ticket quantity given is not valid.',
        ];

        return Validator::make($request->json()->all(), [
            'title' => 'required|min:5',
            'description' => 'required|min:10',
            'privacy' => 'required|in:public,private',
            'end_time' => 'after:start_time',
            'organizer_name' => 'required_if:organizer,new|min:5',
            'tickets' => 'required',
            'tickets.*.name' => 'required_unless:tickets.*.deleted,1',
            'tickets.*.price' => 'required_unless:tickets.*.deleted,1|numeric',
            'tickets.*.quantity' => 'required_unless:tickets.*.deleted,1|integer',
        ], $messages);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $type = Input::get('type', 'latest');

        switch ($type) {
            case "own":
                $events = Event::where([
                    ['owner_id', Auth::guard('api')->id()],
                    ['parent', null],
                    ])->with('owner', 'organizer', 'children', 'tickets')
                    ->latest();
                break;
            case "saved":
                $events = Auth::guard('api')->user()->saved_events()->where([
                    ['privacy', 'public'],
                    ['live', 1]
                    ])->with('owner', 'organizer', 'children', 'tickets');
                break;
            default:
                $events = Event::where([
                    ['end_time', '>', date("Y-m-d H:i:s")],
                    ['privacy', 'public'],
                    ['live', 1],
                    ['parent', null],
                    ])->with('owner', 'organizer', 'children', 'tickets')
                    ->latest();
                break;
        }

        $count = $events->count();
        return response()->json([
            'events' => $events->take(Input::get("take", 10))->skip(Input::get("skip", 0))->get()->toArray(),
            'count' => $count
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->authorizeForUser(Auth::guard('api')->user(), 'create', Event::class);

        $event = Event::create(Input::json()->all());


        $event->owner_id = Auth::guard('api')->id();
        $event->start_time = new DateTime(Input::json()->get('start_time'));
        $event->end_time = new DateTime(Input::json()->get('end_time'));

        $event->slug = $event->title;
        $event->slug = str_slug($event->slug);

        foreach(Input::json()->get('tickets') as $ticket){
            $ticket['privacy'] = 'public';
            $ticket['start_time'] = '0000-00-00 00:00:00';
            $ticket['end_time'] = '9999-12-31 23:59:59';
            $event->tickets()->save(new Ticket($ticket));
        }

        $event->update_meta('online_event', Input::json()->get('online_event'));
        $event->update_meta('location_name', Input::json()->get('location_name'));
        $event->update_meta('location_address', Input::json()->get('location_address'));
        $event->update_meta('location_latitude', Input::json()->get('location_latitude'));
        $event->update_meta('location_longitude', Input::json()->get('location_longitude'));


        if(Input::json()->get('has_new_file')){
            $file = new Base64EncodedFile(Input::json()->get('new_cover_image'));
            $filename = storage_path('uploadtemp').'/'.time().'.jpg';
            $file = $file->move(storage_path('uploadtemp'), time().'.jpg');
            $media = MediaUploader::fromSource($file)
                ->useHashForFilename()
                ->onDuplicateReplace()
                ->toDestination('uploads', 'event/cover_images')
                ->upload();

            $event->attachMedia($media, ['cover_image']);

            unlink($filename);
        }

        $validator = $this->validator($request);

        Event::withoutSyncingToSearch(function () use ($event, $validator){
            if(Input::json()->get('live') && $validator->fails()){
                $event->live = false;
                $event->save();
                return Response::json([
                    'error' => 'validation_failed',
                    'message' => implode("\n\r", $validator->errors()->all())], 400);
            }
            elseif(!Input::json()->get('live')){
                $event->live = false;
            }
            else {
                $event->live = true;
            }
            $event->save();
        });


        if($event->privacy == 'public'){
            $event->searchable();
        }
        else {
            $event->unsearchable();
        }

        return response()->json(self::prepareEvent($event));
    }

    private static function prepareEvent($event){
        if(null != $event->start_time && !is_string($event->start_time))
            $event->start_time = $event->start_time->format('Y-m-d H:i:s');
        if(null != $event->end_time && !is_string($event->end_time))
            $event->end_time = $event->end_time->format('Y-m-d H:i:s');

        $event->location_name = $event->meta('location_name');
        $event->location_latitude = $event->meta('location_latitude');
        $event->location_longitude = $event->meta('location_longitude');
        $event->online_event = $event->meta('online_event') == 1;

        // Just load the following properties no need to change.
        $event->tickets;
        $event->owner;

        return $event;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Event::find($id);
        $this->authorizeForUser(Auth::guard('api')->user(), 'view', $event);
        if( $event == null ) return Response::json([
            'error' => 'not_found',
            'message' => 'Event not found'], 404);



        return response()->json($this->prepareEvent($event));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $event = Event::find($id);

        $this->authorizeForUser(Auth::guard('api')->user(), 'update', $event);

        $event->title = Input::json()->get('title');
        $event->description = Input::json()->get('description');
        $event->privacy = Input::json()->get('privacy');

        if(Input::json()->has('start_time')) $event->start_time = new DateTime(Input::json()->get('start_time'));
        if(Input::json()->has('end_time')) $event->end_time = new DateTime(Input::json()->get('end_time'));

        $event->slug = $event->title;
        $event->slug = str_slug($event->slug);

        foreach(Input::json()->get('tickets') as $ticket){
            if($ticket['deleted'] && $ticket['id'] != 0){
                $ticketModel = Ticket::find($ticket['id']);
                $this->authorizeForUser(Auth::guard('api')->user(), 'delete', $ticketModel);
                $ticketModel->delete();
            }
            else {
                if($ticket['id'] == 0){
                    $ticket['privacy'] = 'public';
                    $ticket['start_time'] = '0000-00-00 00:00:00';
                    $ticket['end_time'] = '9999-12-31 23:59:59';
                    $event->tickets()->save(new Ticket($ticket));
                }
                else {
                    $ticket_e = Ticket::find($ticket['id']);
                    $this->authorizeForUser(Auth::guard('api')->user(), 'update', $ticket_e);
                    $ticket_e->name = $ticket['name'];
                    $ticket_e->description = $ticket['description'];
                    $ticket_e->price = $ticket['price'];
                    $ticket_e->quantity = $ticket['quantity'];
                    $ticket_e->save();
                }
            }
        }

        $event->update_meta('online_event', Input::json()->get('online_event'));
        $event->update_meta('location_name', Input::json()->get('location_name'));
        $event->update_meta('location_address', Input::json()->get('location_address'));
        $event->update_meta('location_latitude', Input::json()->get('location_latitude'));
        $event->update_meta('location_longitude', Input::json()->get('location_longitude'));


        if(Input::json()->get('has_new_file')){
            // Delete any existing cover imag of the same event.
            if($event->hasMedia('cover_image')){
                $event->firstMedia('cover_image')->delete();
            }

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function getIndex()
    {
        return view('home');
    }
}

resources/views/dashboard/events/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Create Event')

@section('content')

<form class="form" action="{{route('events.store')}}" method="post" enctype="multipart/form-data" >

    @if (count($errors) > 0)
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $message)
                        <li>{{$message}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </section>
    @endif

    <!-- General Information about Event -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.general-info')
            </div>
        </div>
    </section>

    <!--  Events Location -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.location')
            </div>
        </div>
    </section>

    <!-- Tickets Create Section -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.ticket-section')
            </div>
        </div>
    </section>

    <!-- Add Organizer Section -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-xs-12">
                @include('dashboard.events.snippets.organizer-list')
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <hr class="org-finish hr-first-child">
                <hr class="org-finish hr-last-child">
            </div>
        </div>
    </section>

    <!-- Form Fields Section -->
    <section class="container section-gap" >
        <div id="form-fields-section" class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.form-fields-section')
            </div>
        </div>
    </section>

    <!-- Add Sub events Section -->
    <section class="container section-gap" >
        <div id="sub-event-section" class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.sub-events')
            </div>
        </div>
    </section>

    <!-- Event Create Button Section-->
    <section class="container section-gap">
        <div class="row">
            <div class="create-event-button">
                <div class="col-sm-offset-2 col-sm-4">
                    <button name="live" value="" type="submit" class="btn btn-secondary">Save Event</button>
                </div>
                <div class="col-sm-4">
                    <button name="live" value="on" class="btn btn-primary">Make Event Live</button>
                    {{ csrf_field() }}
                </div>

            </div>
        </div>
    </section>

</form>
@endsection


@push('scripts')
<script type="text/javascript" src="{{asset('/js/jquery.uploadPreview.min.js')}}"></script>
@endpush

@push('scripts-after')
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_5pvfvn7OmtCQJifqvHo6y3uyzziHV5Y&libraries=places&callback=initMap"></script>
@endpush

resources/views/dashboard/events/edit.blade.php
@extends('layouts.dashboard')

@section('title', 'Edit Event')

@section('content')

<form class="form" action="{{route('events.update', $event->id)}}" method="post" enctype="multipart/form-data">

    @if (count($errors) > 0)

    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $message)
                        <li>{{$message}}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </section>

    @endif

    <!-- General Information about Event -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.general-info')
            </div>
        </div>
    </section>

    <!--  Events Location -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.location')
            </div>
        </div>
    </section>

    <!-- Tickets Create Section -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.ticket-section')
            </div>
        </div>
    </section>

    <!-- Add Organizer Section -->
    <section class="container section-gap">
        <div class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.organizer-list')
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <hr class="org-finish hr-first-child">
                <hr class="org-finish hr-last-child">
            </div>
        </div>
    </section>

    <!-- Form Fields Section -->
    <section class="container section-gap" >
        <div id="form-fields-section" class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.form-fields-section')
            </div>
        </div>
    </section>

    <!-- Add Sub events Section -->
    <section class="container section-gap" >

        <div id="sub-event-section" class="row">
            <div class="col-sm-12">
                @include('dashboard.events.snippets.sub-events')
            </div>
        </div>
    </section>

    <!-- Event Create Button Section-->
    <section class="container section-gap">
        <div class="row">
            <div class="create-event-button">
                <div class="col-sm-offset-2 col-sm-4">
                    <button name="save" value="" type="submit" class="btn btn-secondary">
                        @if($event->live)
                            Update &amp; Unpublish
                        @else
                            Save Event
                        @endif
                    </button>
                </div>
                <div class="col-sm-4">
                    <button name="live" value="on" class="btn btn-primary">
                        @if($event->live)
                            Update
                        @else
                            Make Event Live
                        @endif
                    </button>
                </div>

            </div>
        </div>
    </section>

    {{ csrf_field() }}
    {{ method_field('PUT') }}

</form>
<div class="lemmmin-float-bar">
    <a class="active lem-back" href="{{ route('events.index')}}"><i class="fa fa-chevron-left"></i></a>
    @can('see_guests', $event)
    <a class="lem-guest" href="{{ route('events.guests', $event)}}"><i class="fa fa-users"></i></a>
    @endcan
    <a class="lem-view" href="{{ route('events.show', $event)}}"><i class="fa fa-eye"></i></a>
    @can('delete', $event)
    <form  action="{{route('events.destroy', $event->id)}}" method="post">
        <button type="submit" class="lem-trash">
            <i class="fa fa-trash"></i>
        </button>
        {{ csrf_field() }}
        {{ method_field('DELETE') }}
    </form>
    @endcan
</div>
@endsection


@push('scripts')
<script type="text/javascript" src="{{asset('/js/jquery.uploadPreview.min.js')}}"></script>
@endpush

@push('scripts-after')
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_5pvfvn7OmtCQJifqvHo6y3uyzziHV5Y&libraries=places&callback=initMap"></script>
@endpush

resources/views/dashboard/events/export_codes.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Export Pass QR Codes for {{$event->title}}</title>
        <link href="{{ elixir('css/bootstrap.min.css') }}" rel="stylesheet">
    </head>
    <body>

        <div class="container">
            @foreach($passes as $pass)
            <div class="code_unit">
                <img class="img-responsive" src="data:image/png;base64, {!! base64_encode(QrCode::format('png')->color((int) $colors[0], (int) $colors[1], (int) $colors[2])->size(100)->margin(1)->generate($pass->pass_number)) !!} ">
                <br>
                <div class="pass_id">
                    <span>{{$pass->pass_number}}</span>
                </div>
            </div>
            @endforeach

            <div class="clearfix"></div>

            <div class="text-center">
                {{ $passes->links() }}
            </div>
        </div>

        <style>
            .code_unit {
                float:left;
                width:0.9in;
                margin:0.05in;
                position:relative;
            }
            .code_unit img {
                margin: 0;
                max-width: 100%;
                display: inline-block;
            }
            .pass_id {
                text-align:center;
                margin: 0;
                margin-top: -5px;
            }

            .pass_id span {
                background-color: white;
                font-size: 8pt;
            }
        </style>

        <style media="print">
            .container {
                width: 8.5in;
            }
            .pagination {
                display: none;
            }
        </style>

    </body>
</html>

resources/views/dashboard/events/guests.blade.php
@extends('layouts.dashboard')

@section('title', $event->title)

@section('content')
    <section class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Pass#</th>
                                <th>User</th>
                                <th>Ticket Type</th>
                                <th>Order#</th>
                                <th>Status</th>
                                <th>Purchased On</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($passes as $pass)
                            <tr>
                                <td><a href="{{route('passes.show', $pass->pass_number)}}">{{$pass->pass_number}}</a></td>
                                <td>{{$pass->user->name}}</td>
                                <td>{{$pass->ticket_name}}</td>
                                <td>{{$pass->order_id}}</td>
                                <td>{{$pass->status}}</td>
                                <td>{{$pass->created_at}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    <div class="text-center">
                        {{$passes->links()}}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/dashboard/events/index.blade.php
@extends('layouts.dashboard')

@section('title', 'All My Events')

@section('content')

<section class="container section-gap">
    <div class="row">
        <div class="col-sm-12">
            @if(count($events))
            <div class="row">
                @each('dashboard.events.snippets.event', $events, 'event')
            </div>
            @else
            @include('dashboard.events.snippets.no-events')
            @endif
            <div class="text-center">
                {{ $events->links() }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-4 col-sm-4">
                <a href="{{route('events.create')}}" class="btn btn-primary btn-slim btn-fullwidth">Create New</a>
            </div>
        </div>
    </div>
</section>
@endsection