app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;
use App\Event;

Route::group(['middleware' => ['web']], function () {
	Route::auth();
	Route::get('/registration/{user}/{confirmation_code}', 'Auth\RegisterController@activate')
			 ->name('registration.activate');

	Route::group(['prefix' => 'social'], function(){
		Route::get('facebook', 'SocialAuthController@facebook');
		Route::get('facebook/callback', 'SocialAuthController@facebookCallback');
		Route::get('google', 'SocialAuthController@google');
		Route::get('google/callback', 'SocialAuthController@googleCallback');
	});


	// Route for purchase ticket form submission
	Route::post('events/{event}/tickets', 'OrderController@postPurchaseTicket')
	->name('events.tickets');
	Route::get('order/prepare', 'OrderController@getPrepareOrder')
	->name('orders.prepare');
	Route::post('orders/{order}', 'OrderController@form_submit')
	->name('orders.form_submit');
	Route::get('orders/{order}', 'OrderController@show')
	->name('orders.show');
    Route::post('orders/{order}/pay', 'OrderController@postInitPayment')
        ->name('orders.payment');
    Route::get('orders/{order}/resurrect', 'OrderController@resurrectOrder')
        ->name('orders.resurrect');
	Route::post('payment/{order}/failed', 'OrderController@postFailedTransaction')
	->name('orders.failed_transaction');
	Route::post('payment/{order}/success', 'OrderController@postSuccessfulTransaction')
	->name('orders.successful_transaction');

	Route::get('events/{event}/guests', 'EventController@guestList')->name('events.guests');
	Route::get('events/{event}/export_codes', 'EventController@exportCodes')->name('events.export_codes');
	Route::get('events/{event}/export_csv', 'EventController@exportCsv')->name('events.export_csv');
	Route::get('search', 'EventController@search')->name('search');

	Route::resource('organizers', 'OrganizerController');

	Route::get('events/saved', 'EventController@savedEvents')->name('events.saved');
	Route::get('events/{event}/bookmark', 'EventController@bookmark')->name('events.bookmark');
	Route::resource('events', 'EventController');
	Route::resource('passes', 'PassController',
	['only' => ['index', 'show']]);

	Route::get('/', 'HomeController@getIndex')->name('home');
	Route::get('/browse', 'HomeController@getBrowse')->name('browse');

	Route::get('/terms-of-service', function(){
		return view('pages.tos');
	})->name('tos');

	Route::get('/about-us', function(){
		return view('pages.about');
	})->name('about');

	Route::get('/privacy-policy', function(){
		return view('pages.pp');
	})->name('pp');

	Route::get('/my_profile', 'ProfileController@edit')->name('profiles.self.edit');
	Route::get('/profiles/{user}/edit', 'ProfileController@edit')->name('profiles.edit');
	Route::post('/profiles/{user}/edit', 'ProfileController@update')->name('profiles.update');
});

Route::group([
		'middleware' => ['auth:api', 'api'],
		'prefix' => 'api',
		'as' => 'api::',
	], function () {

		Route::get('events/{event}/bookmark', 'Api\EventController@bookmark')->name('events.bookmark');
		Route::post('events/{event}/scan', 'Api\EventController@scan')->name('events.scan');
		Route::resource('events', 'Api\EventController',
			['except' => ['create', 'edit']]);
		Route::resource('passes', 'Api\PassController',
			['only' => ['index', 'show']]);

		Route::post('orders', 'Api\OrderController@placeOrder');
		Route::post('order/pay/{order}', 'Api\OrderController@postConfirmBkashPayment');

		Route::get('userinfo', 'Api\BasicController@userinfo');
});



Route::post('oauth/provider/{provider}', 'SocialAuthController@authorizeProviderToken')
	->middleware('api');

Route::post('api/users', 'Auth\RegisterController@apiCreate')->middleware(['api', 'auth:api']);

app/Event.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Plank\Mediable\Mediable;
use Carbon\Carbon;
use Laravel\Scout\Searchable;
use App\Event;
use App\Permission;
use Auth;
use LemmminHelper;

class Event extends Model
{
    use Mediable, Metabble, Searchable;


    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'live' => 'boolean',
    ];


    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'location_name',
        'location_address',
        'location_latitude',
        'location_longitude',
        '_geoloc',
        'online_event',
        'cover_image',
        'thumbnail',
        'has_image',
        'is_bookmarked',
        'permissions',
        'max_ticket_purchase',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'slug',
        'start_time',
        'end_time',
        'summary',
        'description',
        'privacy',
        'live',
    ];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('root', function(Builder $builder) {
            $builder->whereNull('parent');
        });
    }

    /**
     * Get the owner of the event
     */
    public function owner()
    {
    	return $this->belongsTo('App\User', 'owner_id');
    }

    /**
     * Get the organizer of the event
     */
    public function organizer()
    {
    	return $this->belongsTo('App\Organizer', 'organizer_id');
    }

    /**
     * Get the child events of this event
     */
    public function children()
    {
        return $this->hasMany('App\Event', 'parent')->withoutGlobalScope('root');
    }

    /**
     * Get the parent event of this event
     */
    public function parent()
    {
        return $this->belongsTo('App\Event', 'parent');
    }

    /**
     * Get tickets associated with this event
     */
    public function tickets()
    {
        return $this->belongsToMany('App\Ticket');
    }

    /**
     * Get passes associated with this event
     */
    public function passes()
    {
        return $this->hasMany('App\Pass');
    }

    /**
     * Get guests of this event
     */
    public function guests()
    {
        return $this->belongsToMany('App\User', 'passes');
    }

    /**
     * Get list of form fields for this event
     */
    public function form_fields()
    {
        return $this->hasMany('App\FormField');
    }

    /**
     * List of orders associated with this event.
     */
    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    /**
     * Find all users that have any permission on this event.
     */
    public function permittedUsers()
    {
        return $this->morphToMany('App\User', 'permissionable');
    }

    /**
     * Find users who have a particular permission on this event.
     */
    public function findUsersByPermission($permission)
    {
        return $this->permittedUsers()
                    ->wherePivot('permission', $permission)
                    ->wherePivot('granted', 1);
    }

    /**
     * Get latitude of a location.
     */
    public function getLocationNameAttribute()
    {
        return $this->meta('location_name');
    }

    /**
     * Get latitude of a location.
     */
    public function getLocationAddressAttribute()
    {
        return $this->meta('location_address');
    }

    /**
     * Get latitude of a location.
     */
    public function getLocationLatitudeAttribute()
    {
        return $this->meta('location_latitude');
    }

    /**
     * Get longitude of a location.
     */
    public function getLocationLongitudeAttribute()
    {
        return $this->meta('location_longitude');
    }

    /**
     * Get longitude of a location.
     */
    public function getOnlineEventAttribute()
    {
        return $this->meta('online_event') == 1;
    }

    public function getCoverImageAttribute()
    {
        if($this->hasMedia('cover_image')){
            $media = $this->firstMedia('cover_image');

            return asset('/images/original/'.$media->basename);
        }

        return asset('/images/original/placeholder.jpg');
    }

    public function getThumbnailAttribute()
    {
        if($this->hasMedia('cover_image')){
            $media = $this->firstMedia('cover_image');

            return asset('/images/large/'.$media->basename);
        }

        return asset('/images/large/placeholder.jpg');
    }

    public function getHasImageAttribute()
    {
        return $this->hasMedia('cover_image');
    }

    public function getStartTimeObjectAttribute()
    {
        return new Carbon($this->start_time);
    }

    public function getEndTimeObjectAttribute()
    {
        return new Carbon($this->end_time);
    }

    public function getGeolocAttribute()
    {
        return [
            'lat' => (float) $this->location_latitude,
            'lng' => (float) $this->location_longitude,
        ];
    }

    public function getIsBookmarkedAttribute()
    {
        if(!Auth::check() && !Auth::guard('api')->check()) return false;

        if(Auth::check()) $user = Auth::user();
        else $user = Auth::guard('api')->user();

        return $user->saved_events()->where('event_id', $this->id)->count() > 0;
    }

    /**
     * Get a list of permission assigned to current user.
     */
    public function getPermissionsAttribute()
    {
        if(Auth::check()) $user = Auth::user();
        else $user = Auth::guard('api')->user();

        // if(is_null($user)) return [];

        $tasks = [
            'view',
            'see_guests',
            'create',
            'update',
            'delete',
        ];

        $permissions = [];
        foreach($tasks as $task){
            $permissions[$task] = $user->can($task, $this);
        }

        return $permissions;
    }

    /**
     * Get maximum number of tickets that can be purchased by a single user.
     */
    public function getMaxTicketPurchaseAttribute()
    {
      return $this->meta('max_ticket_purchase_quantity', 0) == 0 ? LemmminHelper::$max_ticket_per_order : $this->meta('max_ticket_purchase_quantity');
    }

    /**
     * Get maximum number of tickets that can be purchased by current user.
     */
    public function getUserMaxTicketPurchaseAttribute()
    {
      if(!Auth::check()) return $this->max_ticket_purchase;

      return $this->max_ticket_purchase - $this->passes()->where('user_id', Auth::id())->count();
    }

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        $array = $this->toArray();

        $array['created_at'] = strtotime($array['created_at']);
        $array['updated_at'] = strtotime($array['updated_at']);
        $array['start_time'] = strtotime($array['start_time']);
        $array['end_time'] = strtotime($array['end_time']);

        return $array;
    }

    /**
     * Strip event from all the dependents
     */
    public function deleteRelatives()
    {
        foreach($this->children()->get() as $child){
            $child->deleteRelatives();
            $child->delete();
        }

        $tickets = $this->tickets()->get();

        foreach($tickets as $ticket){
            $this->tickets()->detach($ticket->id);

            if(count($ticket->events()) > 0)
                Ticket::destroy($ticket->id);
        }
    }
}

resources/views/frontend/snippets/event.blade.php
@php
$event = (object) $event;
@endphp


<div class="col-sm-4">
    <div id="event-{{$event->id}}">
        <div class="single-event-card">

            <div class="single-event-card-cover-image">
                <a href="{{route('events.show', $event->id)}}">
                    <img class="img-responsive" src="{{$event->thumbnail}}" alt="Cover Image">
                </a>
            </div>
            <div class="single-event-card-short-data">
                <div class="row">
                    <div class="col-xs-2">
                        <div class="single-event-card-date-box">
                            {!! $event->start_time_object->format('<p>j <b\r />M</p>') !!}
                        </div>
                    </div>
                    <div class="col-xs-10">
                        <div class="single-event-card-heading">
                            <h4 >
                                <a href="{{route('events.show', $event->id)}}">
                                    @if(strlen($event->title) < 30)
                                    {{$event->title}}
                                    @else
                                    {{mb_substr($event->title,0,30,'UTF-8')}} . . .
                                    @endif
                                </a>
                            </h4>
                            @if($event->organizer != null)
                                <p >Organized By <a href="{{route('organizers.show', $event->organizer)}}">{{$event->organizer->name}}</a></p>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-offset-2 col-xs-10">
                        <div class="single-event-card-description">
                            <p>
                                @if(strlen($event->description) < 100)
                                    {{$event->description}}
                                @else
                                    {{mb_substr($event->description,0,100,'UTF-8')}} . . .
                                @endif
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single-event-card-footer">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="single-event-card-footer-privacy">
                            {{$event->privacy}}
                        </div>

                        <div class="single-event-card-footer-share">
                            <a class="fa fa-share-alt addthis_button_compact"
                            addthis:url="{{route('events.show', $event)}}"
                            addthis:title="{{$event->title}}"></a>
                        </div>

                        <div class="single-event-card-footer-bookmark">
                            <a href="{{route('events.bookmark', $event)}}" class="fa {{$event->is_bookmarked ? 'fa-bookmark' : 'fa-bookmark-o'}} save_event"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/frontend/snippets/latest-event.blade.php
@php
$event = (object) $event;

$eventStartDate = $event->start_time_object->format('jS F Y');

@endphp

<div class="col-sm-12">
    <div class="row">
        <div class="col-sm-5">
            <img class="img-responsive" src="{{$event->cover_image}}" alt="cover image">
        </div>
        <div class="col-sm-7">
            <h4>$event->title</h4>
            <div class="row">
                <div class="col-xs-4">
                    <p>$eventStartDate</p>
                </div>
                <div class="col-xs-4">
                    <p>$event->$ticket->price</p>
                </div>
                <div class="col-xs-4">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="{{route('events.bookmark', $event)}}" class="fa {{$event->is_bookmarked ? 'fa-heart' : 'fa-heart-o'}} save_event"></a>
                        </div>
                        <div class="col-xs-6">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="single-event-card-description">
                        <p>
                            @if(strlen($event->description) < 300)
                                {{$event->description}}
                            @else
                                {{substr($event->description,0,300)}} . . .
                            @endif
                        </p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <button class="btn btn-primary btn-slim btn-fullwidth" type="submit" name="button">Buy Tickets</button>

                </div>
                <div class="col-sm-6">
                    <button class="btn btn-primary btn-slim btn-fullwidth" type="submit" name="button">View Details</button>
                </div>
            </div>
        </div>
    </div>
</div>