app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

use Illuminate\Http\Request;
use App\Event;

Route::group(['middleware' => ['web']], function () {
	Route::auth();
	Route::get('/registration/{user}/{confirmation_code}', 'Auth\RegisterController@activate')
			 ->name('registration.activate');

	Route::group(['prefix' => 'social'], function(){
		Route::get('facebook', 'SocialAuthController@facebook');
		Route::get('facebook/callback', 'SocialAuthController@facebookCallback');
		Route::get('google', 'SocialAuthController@google');
		Route::get('google/callback', 'SocialAuthController@googleCallback');
	});


	// Route for purchase ticket form submission
	Route::post('events/{event}/tickets', 'OrderController@postPurchaseTicket')
	->name('events.tickets');
	Route::get('order/prepare', 'OrderController@getPrepareOrder')
	->name('orders.prepare');
	Route::post('orders/{order}', 'OrderController@form_submit')
	->name('orders.form_submit');
	Route::get('orders/{order}', 'OrderController@show')
	->name('orders.show');
    Route::post('orders/{order}/pay', 'OrderController@postInitPayment')
        ->name('orders.payment');
    Route::get('orders/{order}/resurrect', 'OrderController@resurrectOrder')
        ->name('orders.resurrect');
	Route::post('payment/{order}/failed', 'OrderController@postFailedTransaction')
	->name('orders.failed_transaction');
	Route::post('payment/{order}/success', 'OrderController@postSuccessfulTransaction')
	->name('orders.successful_transaction');

	Route::get('events/{event}/guests', 'EventController@guestList')->name('events.guests');
	Route::get('events/{event}/export_codes', 'EventController@exportCodes')->name('events.export_codes');
	Route::get('events/{event}/export_csv', 'EventController@exportCsv')->name('events.export_csv');
	Route::get('search', 'EventController@search')->name('search');

	Route::resource('organizers', 'OrganizerController');

	Route::get('events/saved', 'EventController@savedEvents')->name('events.saved');
	Route::get('events/{event}/bookmark', 'EventController@bookmark')->name('events.bookmark');
	Route::resource('events', 'EventController');
	Route::resource('passes', 'PassController',
	['only' => ['index', 'show']]);

	Route::get('/', 'HomeController@getIndex')->name('home');
	Route::get('/browse', 'HomeController@getBrowse')->name('browse');

	Route::get('/terms-of-service', function(){
		return view('pages.tos');
	})->name('tos');

	Route::get('/about-us', function(){
		return view('pages.about');
	})->name('about');

	Route::get('/privacy-policy', function(){
		return view('pages.pp');
	})->name('pp');

	Route::get('/my_profile', 'ProfileController@edit')->name('profiles.self.edit');
	Route::get('/profiles/{user}/edit', 'ProfileController@edit')->name('profiles.edit');
	Route::post('/profiles/{user}/edit', 'ProfileController@update')->name('profiles.update');
});

Route::group([
		'middleware' => ['auth:api', 'api'],
		'prefix' => 'api',
		'as' => 'api::',
	], function () {

		Route::get('events/{event}/bookmark', 'Api\EventController@bookmark')->name('events.bookmark');
		Route::post('events/{event}/scan', 'Api\EventController@scan')->name('events.scan');
		Route::resource('events', 'Api\EventController',
			['except' => ['create', 'edit']]);
		Route::resource('passes', 'Api\PassController',
			['only' => ['index', 'show']]);

		Route::post('orders', 'Api\OrderController@placeOrder');
		Route::post('order/pay/{order}', 'Api\OrderController@postConfirmBkashPayment');

		Route::get('userinfo', 'Api\BasicController@userinfo');
});



Route::post('oauth/provider/{provider}', 'SocialAuthController@authorizeProviderToken')
	->middleware('api');

Route::post('api/users', 'Auth\RegisterController@apiCreate')->middleware(['api', 'auth:api']);

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use Input;
use Response;
use App\Order;
use App\Ticket;
use App\Transaction;
use App\OrderQuantity;
use App\Jobs\InvalidateOrder;
use Carbon\Carbon;
use LemmminHelper;

class OrderController extends Controller
{
    public function placeOrder()
    {
        $tickets = Input::json()->all();
        $tickets = array_filter($tickets, function($t){
            return $t['mCount'] > 0;
        });

        // return var_dump($tickets);

        if(count($tickets) > LemmminHelper::$max_ticket_per_order){
            return Response::json([
                'error' => 'too_many_tickets',
                'message' => sprintf("Total ticket quantity must be under %d.", LemmminHelper::$max_ticket_per_order)], 400);
        }
        elseif(count($tickets) < 1){
            return Response::json([
                'error' => 'no_ticket',
                'message' => 'You did not select any ticket to order.'], 400);
        }

        $order = Order::create([
            'user_id' => Auth::guard('api')->id(),
            'status' => 'pending',
        ]);


        $rows = [];
        $total = 0;
        foreach($tickets as $cart_item){
            $ticket = Ticket::find($cart_item['mTicketType']['id']);
            if(is_null($ticket)) continue;

            if($ticket->remaining < $cart_item['mCount'] || $ticket->max_purchase < $cart_item['mCount']){
                return Response::json([
                    'error' => 'not_available',
                    'message' => 'Looks like someone else already purchased tickets. Try decreasing some.'], 400);
            }

            $rows[] = [
                'order_id' => $order->id,
                'ticket_id' => $ticket->id,
                'ticket_name' => $ticket->name,
                'event_id' => $ticket->events[0]->id,
                'quantity' => $cart_item['mCount'],
                'price' => $ticket->price,
            ];

            $ticket->issued += $cart_item['mCount'];
            $ticket->save();

            $total += $cart_item['mCount']*$ticket->price;
        }


        OrderQuantity::insert($rows);

        $order->update_meta('total', $total);

        if($total == 0 && $order->generatePasses()){
            $order->status = 'complete';
            $order->save();
        }
        else {
            $invalidateJob = new InvalidateOrder($order);
            $invalidateJob->delay(Carbon::now()->addMinutes(LemmminHelper::$order_reserve_duration));
            dispatch($invalidateJob);
        }

        $order->total = $total;
        $order->quantities;
        return $order;
    }

    public function postConfirmBkashPayment($id)
    {
        $order = Order::find($id);
        $this->authorizeForUser(Auth::guard('api')->user(), 'show', $order);

        $transaction = Transaction::where([
            ['status', '=' ,'detached'],
            ['gateway', '=' ,'bkash'],
            ['referance', '=' ,trim(Input::get('bkash_transaction_id'))],
            ['amount', '>=', round($order->meta('total'))],
        ])->first();

        if(is_null($transaction)){
            return Response::json([
                'error' => 'invalid_referance',
                'message' => 'The transaction id is already used or not valid.'], 400);
        }

        if($order->generatePasses()){
            $transaction->status = 'complete';
            $transaction->order()->associate($order);
            $order->status = 'complete';
            $order->save();
            $transaction->save();
        }

        return $order;
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Jobs\InvalidateOrder;
use App\Event;
use App\Order;
use App\OrderQuantity;
use App\Ticket;
use App\Pass;
use App\Transaction;
use App\FormField;
use Input;
use Auth;
use Redirect;
use Response;
use LemmminHelper;
use Carbon\Carbon;
use Validator;
use Session;
use Mail;
use App\Mail\PassesCreated;


class OrderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['postPurchaseTicket']]);
    }


    /**
     * Handle form submission to purchase ticket after selecting.
     */
    public function postPurchaseTicket($id)
    {
        $event = Event::find($id);
        if(is_null($event) || !$event->live){
            return redirect()->route('events.show', $event);
        }

        $tickets = Input::get('tickets');
        $tickets = array_filter($tickets, function($t){
            return $t > 0;
        });

        $total_tickets_count = array_sum($tickets);

        $users_ticket_count = Auth::check() ? $event->passes()->where('user_id', Auth::id())->count() : 0;
        if($total_tickets_count + $users_ticket_count > $event->max_ticket_purchase ){
            abort(500, 'Too many tickets!');
        }
        elseif($total_tickets_count < 1){
            return back();
        }

        session(['tickets' => $tickets]);
        session(['event_id' => $event->id]);

        return redirect()->route('orders.prepare');
    }

    /**
     * Prepare the order to purchase tickets.
     */
    public function getPrepareOrder(Request $request)
    {
        if(!Session::has('event_id') || !Session::has('tickets')) return redirect()->route('home');

        $event = Event::find(session('event_id'));
        $tickets = session('tickets');
        $request->session()->forget(['event_id', 'tickets']);

        $users_ticket_count = $event->passes()->where('user_id', Auth::id())->count();
        if($users_ticket_count > $event->max_ticket_purchase ){
            abort(500, 'Too many tickets!');
        }

        $order = Order::create([
            'user_id' => Auth::id(),
            'status' => 'pending',
            'event_id' => $event->id,
        ]);


        $rows = [];
        $total = 0;
        foreach($tickets as $ticket_id => $quantity){
            $ticket = Ticket::find($ticket_id);
            if(is_null($ticket)) continue;

            if($ticket->remaining < $quantity){
                abort(500, 'Not enough tickets available.');
            }
            if($ticket->user_remaining < $quantity){
                abort(403, 'Not enough tickets available for you.');
            }

            $rows[] = [
                'order_id' => $order->id,
                'ticket_id' => $ticket->id,
                'ticket_name' => $ticket->name,
                'event_id' => $ticket->events[0]->id,
                'quantity' => $quantity,
                'price' => $ticket->price,
            ];

            $ticket->issued += $quantity;
            $ticket->save();

            $total += $quantity*$ticket->price;
        }


        OrderQuantity::insert($rows);

        $order->update_meta('total', $total);
        $order->update_meta('fees', $total / 100 * LemmminHelper::$processing_fee_percent);
        $order->update_meta('fee_percentage', LemmminHelper::$processing_fee_percent);

        if($event->form_fields()->count() != 0){
            $order->status = 'pending_form';
            $order->save();
        }

        $this->generatePasses($order);

        $invalidateJob = new InvalidateOrder($order);
        $invalidateJob->delay(Carbon::now()->addMinutes(LemmminHelper::$order_reserve_duration));
        dispatch($invalidateJob);

        return redirect()->route('orders.show', $order->id);
    }

    /**
     * Get a link to payment url and forward user to that.
     */
    public function postInitPayment(Request $request, $id)
    {
        $order = Order::find($id);
        $this->authorize('pay', $order);


        $validator = Validator::make($request->all(), [
            'email' => 'email',
            'phone' => 'not_in:0',
        ]);
        $validator->sometimes('email', 'required|email', function() use ($order){
            return $order->user->email == '';
        });

        $validator->sometimes('phone', 'required', function() use ($order){
            return $order->user->meta('phone') == '';
        });

        $validator->validate();

        if(Input::has('email')){
            $order->user->email = Input::get('email');
            $order->user->save();
        }
        if(Input::has('phone')){
            $order->user->update_meta('phone', Input::get('phone'));
        }

        if($order->meta('total') < LemmminHelper::$minimum_payment)
            return redirect()->route('orders.show', $order->id);

        $processing_fee = $order->meta('fees');
        $amount_total = $order->meta('total')+$processing_fee;
        $processing_fee_percent = $order->meta('fee_percentage');


        $url = config('services.epw.url').'payment/request.php';

        $domain = config('app.url'); // or Manually put your domain name
        $ip = $_SERVER["SERVER_ADDR"];

        $fields = [
            'store_id' => config('services.epw.store_id'),
            'signature_key' => config('services.epw.signature_key'),
            'amount' => floatval($amount_total),
            'tran_id' => "Order#$id-".time(),
            'success_url' => route('orders.successful_transaction', $order->id),
            'fail_url' => route('orders.failed_transaction', $order->id),
            'cancel_url' => route('orders.failed_transaction', $order->id),
            'currency' => 'BDT',
            'amount_processingfee' => $processing_fee,
            'amount_processingfee_ratio' => $processing_fee_percent,
            'desc' => "Payment for lemmmin order#$id.",
            'cus_name' => $order->user->name,
            'cus_email' => $order->user->email,
            'cus_add1' => $order->user->meta('address_line_1'),
            'cus_add2' => $order->user->meta('address_line_2'),
            'cus_city' => $order->user->meta('city'),
            'cus_state' => $order->user->meta('district'),
            'cus_postcode' => $order->user->meta('postcode'),
            'cus_country' => 'Bangladesh',
            'cus_phone' => $order->user->meta('phone'),
            'opt_a' => $id,
            'opt_b' => Auth::id(),
        ];

        // $fields_string = '';
        // //url-ify the data for the POST
        // foreach($fields as $key=>$value) { $fields_string .= $key.'='.$value.'&'; }
        // rtrim($fields_string, '&');

        $ch = curl_init();

        //set the url, number of POST vars, POST data

        curl_setopt( $ch, CURLOPT_HTTPHEADER, array("REMOTE_ADDR: $ip", "HTTP_X_FORWARDED_FOR: $ip"));
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_REFERER, $domain);
        curl_setopt($ch, CURLOPT_INTERFACE, $ip);
        curl_setopt($ch, CURLOPT_POST, count($fields));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        //execute post

        $result = curl_exec($ch);

        $url = json_decode($result, true);

        if(!filter_var($url, FILTER_VALIDATE_URL, FILTER_FLAG_QUERY_REQUIRED) === false)
            return Redirect::to($url);

        abort(500, $url);
    }

    /**
     * Handle a failed transaction.
     */
    public function postFailedTransaction($id)
    {
        return redirect()->route('orders.show', $id)->withErrors([Input::get('reason')]);
    }

    /**
     * Handle a successful transaction.
     */
    public function postSuccessfulTransaction($id)
    {
        $order = Order::find($id);
        $this->authorize('pay', $order);

        if(Input::get('pay_status') != "Successful"){
            return print_r(Input::all(), 1);

            return redirect()->route('orders.show', $id);
        }

        $url = config('services.epw.url').'api/v1/trxcheck/request.php';
        $url .= '?';
        $url .= http_build_query([
            'request_id' => Input::get('mer_txnid'),
            'store_id' => config('services.epw.store_id'),
            'signature_key' => config('services.epw.signature_key'),
            'type' => 'json'
        ]);

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        $result = curl_exec($ch);

        $data = json_decode($result);

        if(
            $data->amount < $order->meta('total') + $order->meta('fees') ||
            $data->risk_level != 0 ||
            $data->status_code != 2 ||
            $data->opt_a != $id
        ){
            return redirect()->route('orders.show', $id)
                ->withErrors([
                    "Could not verify transaction. Please contact with referance {$data->mer_txnid}"
                ]);
        }

        $transaction = Transaction::create([
            'referance' => $data->mer_txnid,
            'amount' => $data->amount,
            'currency' => $data->currency,
            'gateway' => $data->payment_type,
            'note' => 'epw_txnid: '.$data->epw_txnid,
            'status' => 'successful'
        ]);

        $order->passes()->update(['status' => 'valid']);
        $transaction->status = 'complete';
        $transaction->order()->associate($order);
        $order->status = 'complete';

        $this->sendPasses($order);

        $order->save();
        $transaction->save();



        return redirect()->route('orders.show', $order);
    }

    /**
     * Show an order page.
     */
    public function show($id){
        $order = Order::find($id);

resources/views/orders/form.blade.php
@extends('layouts.dashboard')

@section('title', "Order# $order->id")

@section('content')
    <script>
    fbq('track', 'Form');
    </script>
    <section class="container">
        <div class="row">
            <div class="col-sm-12">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $message)
                            <li>{{$message}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <p class="alert alert-warning">
                    This order will expire on
                    {{$order->created_at
                        ->addMinutes(LemmminHelper::$order_reserve_duration)
                        ->timezone('Asia/Dhaka')
                        ->toDayDateTimeString()}}
                    unless paid.
                </p>
            </div>
        </div>

        <form class="order-form" action="{{route('orders.form_submit', $order)}}" method="post">
            @foreach($order->passes as $i => $pass)
                <div class="box">
                    <h2>Pass#: {{$pass->passNumber}}</h2>
                    <p><b>Pass Type:</b> {{$pass->ticket_name}}</p>

                    @foreach($order->event->form_fields as $j => $field)
                        <div class="field">
                            @if(in_array($field->type, ['radio', 'checkbox']))
                            <label for="">{{$field->title}}</label>
                            @else
                            <label for="field-{{$i}}-{{$j}}">{{$field->title}}</label>
                            @endif

                            @php
                            $options = preg_split('/\r\n|[\r\n]/', $field->options);
                            @endphp

                            @if($field->type == 'text')
                                <input
                                    type="text"
                                    id="field-{{$i}}-{{$j}}"
                                    class="form-control"
                                    name="field[{{$pass->id}}][{{$field->id}}]"
                                    value="{{old('field.'.$pass->id.'.'.$field->id)}}"
                                    {{$field->required ? 'required="required"':''}}>
                            @elseif($field->type == 'email')
                                <input
                                    type="email"
                                    id="field-{{$i}}-{{$j}}"
                                    class="form-control"
                                    name="field[{{$pass->id}}][{{$field->id}}]"
                                    value="{{old('field.'.$pass->id.'.'.$field->id)}}"
                                    {{$field->required ? 'required="required"':''}}>
                            @elseif($field->type == 'paragraph')
                                <textarea
                                    name="field[{{$pass->id}}][{{$field->id}}]"
                                    id="field-{{$i}}-{{$j}}"
                                    class="form-control"
                                    {{$field->required ? 'required="required"':''}}>{{old('field.'.$pass->id.'.'.$field->id)}}</textarea>
                            @elseif($field->type == 'select')
                                <select
                                    name="field[{{$pass->id}}][{{$field->id}}]"
                                    id="field-{{$i}}-{{$j}}"
                                    class="form-control"
                                    {{$field->required ? 'required="required"':''}}>
                                    @foreach($options as $option)
                                        <option
                                            value="{{$option}}"
                                            {{old('field.'.$pass->id.'.'.$field->id) == $option ? 'selected="selected"': ''}}>{{$option}}</option>
                                    @endforeach
                                </select>
                            @elseif($field->type == 'radio')
                                @foreach($options as $option)
                                    <div class="radio">
                                        <label>
                                            <input type="radio"
                                                value="{{$option}}"
                                                name="field[{{$pass->id}}][{{$field->id}}]"
                                                {{old('field.'.$pass->id.'.'.$field->id) == $option ? 'checked="checked"': ''}}
                                                {{$field->required ? 'required="required"':''}}> {{$option}}
                                        </label>
                                    </div>
                                @endforeach
                            @elseif($field->type == 'checkbox')
                                @foreach($options as $option)
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"
                                                value="{{$option}}"
                                                name="field[{{$pass->id}}][{{$field->id}}][]"
                                                {{in_array($option, (array)old('field.'.$pass->id.'.'.$field->id)) ? 'checked="checked"': ''}}> {{$option}}
                                        </label>
                                    </div>
                                @endforeach
                            @endif
                        </div>
                    @endforeach
                </div>
            @endforeach

            <div class="text-center">
                <button class="btn btn-primary" id="submit-button" type="submit">Continue</button>
                {{csrf_field()}}
            </div>
        </form>
    </section>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.dashboard')

@section('title', "Order# $order->id")

@section('content')
    @if($order->status == 'complete')
    <script>
    fbq('track', 'Purchase');
    </script>
    @endif
    <section class="container">
        <div class="row">
            <div class="col-sm-12">
                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $message)
                            <li>{{$message}}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                @if($order->status == 'pending')
                <p class="alert alert-warning">
                    This order will expire on
                    {{$order->created_at
                        ->addMinutes(LemmminHelper::$order_reserve_duration)
                        ->timezone('Asia/Dhaka')
                        ->toDayDateTimeString()}}
                    unless paid.
                </p>
                @elseif($order->status == 'cancelled')
                <p class="alert alert-danger">
                    This order has been cancelled.
                </p>
                @elseif($order->status == 'expired')
                <p class="alert alert-danger">
                    This order has expired. Please place another order to continue.
                </p>
                @else
                <p class="alert alert-info">
                    Your order information is listed below
                </p>
                @endif
            </div>
        </div>


        <div class="row">
            <div class="col-sm-12">
                <div class="table-responsive">
                    <table class="table order-table">
                        <thead>
                            <tr>
                                <th class="ticket-name">Ticket</th>
                                <th class="ticket-fee">Fee</th>
                                <th class="ticket-quantity">Quantity</th>
                                <th class="ticket-total">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($order->quantities as $row)
                            <tr>
                                <td class="ticket-name">
                                    {{$row->ticket_name}}
                                    @if(!is_null($row->ticket))
                                    <br>
                                    <small>{{$row->ticket->events[0]->title}}</small>
                                    @endif
                                </td>
                                <td class="ticket-fee">৳ {{number_format($row->price, 2, '.', ',')}}</td>
                                <td class="ticket-quantity">{{$row->quantity}}</td>
                                <td class="ticket-total">৳ {{number_format($row->price * $row->quantity, 2, '.', ',')}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                        <tfoot class="order-totals">
                            <tr>
                                <td colspan="2" class="invisible"></td>
                                <td class="order-total">Total</td>
                                <td class="ticket-total">৳ {{number_format($order->meta('total'), 2, '.', ',')}}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="invisible"></td>
                                <td class="order-fee">Processing Fee ({{$order->meta('fee_percentage')}}%)</td>
                                <td class="ticket-total">৳ {{number_format($order->meta('fees'), 2, '.', ',')}}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="invisible"></td>
                                <td class="order-subtotal">Subtotal</td>
                                <td class="ticket-total">৳ {{number_format($order->meta('total') + $order->meta('fees'), 2, '.', ',')}}</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>

        @if($order->status == 'complete')
        <div class="text-center">
            <a href="{{route('passes.index', ['order' => $order->id])}}" class="btn btn-primary pull-right">View your passes</a>
        </div>
        @elseif($order->status == 'pending')
            <form action="{{route('orders.payment', $order)}}" method="post">
                @if($order->user->email == '')
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 form-group">
                        <label for="email">Email</label>
                        <input type="email" name="email" id="email" class="form-control" required>
                    </div>
                </div>
                @endif
                @if($order->user->meta('phone') == '')
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 form-group">
                        <label for="phone">Phone</label>
                        <input type="text" name="phone" id="phone" class="form-control" required>
                    </div>
                </div>
                @endif
                <div class="row">
                    <div class="col-sm-12 text-center"><button type="submit" class="btn btn-primary">Pay &amp; Confirm</button></div>
                </div>
                {{csrf_field()}}
            </form>
        @endif

    </section>
@endsection